#!/usr/bin/env python3
#
# Copyright VyOS maintainers and contributors <maintainers@vyos.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Validate a BGP Autonomous System (AS) number in either plain (asplain) or
# dot (asdot) notation.
#
# asplain: a single decimal integer in the range 1–4294967294
# asdot:   two dot-separated 16-bit integers  X.Y  where
#            0 <= X <= 65535, 0 <= Y <= 65535
#          and the resulting value  X * 65536 + Y  is in 1–4294967294

import sys

from vyos.utils.network import bgp_as_get_integer_value


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(1)

    try:
        bgp_as_get_integer_value(sys.argv[1])
    except ValueError:
        sys.exit(1)

    sys.exit(0)
